
gui.SetValue("esp")
gui.SetValue("esp.chams" )
gui.SetValue("esp.chams.backtrack" )
gui.SetValue("esp.chams.backtrack.glow", "Off")
gui.SetValue("esp.chams.backtrack.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.backtrack.occluded", "Bubble")
gui.SetValue("esp.chams.backtrack.occluded.clr", 45, 165, 200, 150)
gui.SetValue("esp.chams.backtrack.overlay", "Off")
gui.SetValue("esp.chams.backtrack.overlay.clr", 45, 165, 200, 150)
gui.SetValue("esp.chams.backtrack.visible", "Bubble")
gui.SetValue("esp.chams.backtrack.visible.clr", 141, 87, 208, 150)
gui.SetValue("esp.chams.enemy" )
gui.SetValue("esp.chams.enemy.glow", "Off")
gui.SetValue("esp.chams.enemy.glow.clr", 20, 25, 160, 255)
gui.SetValue("esp.chams.enemy.glow.healthclr1", 255, 0, 0, 255)
gui.SetValue("esp.chams.enemy.glow.healthclr2", 0, 255, 0, 255)
gui.SetValue("esp.chams.enemy.occluded", "Bubble")
gui.SetValue("esp.chams.enemy.occluded.clr", 254, 27, 51, 137)
gui.SetValue("esp.chams.enemy.overlay", "Off")
gui.SetValue("esp.chams.enemy.overlay.clr", 10, 10, 10, 127)
gui.SetValue("esp.chams.enemy.visible", "Glow")
gui.SetValue("esp.chams.enemy.visible.clr", 243, 70, 105, 143)
gui.SetValue("esp.chams.enemyattachments" )
gui.SetValue("esp.chams.enemyattachments.glow", "Off")
gui.SetValue("esp.chams.enemyattachments.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.enemyattachments.occluded", "Off")
gui.SetValue("esp.chams.enemyattachments.occluded.clr", 57, 57, 57, 255)
gui.SetValue("esp.chams.enemyattachments.overlay", "Off")
gui.SetValue("esp.chams.enemyattachments.overlay.clr", 239, 199, 53, 150)
gui.SetValue("esp.chams.enemyattachments.visible", "Off")
gui.SetValue("esp.chams.enemyattachments.visible.clr", 239, 199, 53, 255)
gui.SetValue("esp.chams.enemyragdoll")
gui.SetValue("esp.chams.enemyragdoll.glow", "Off")
gui.SetValue("esp.chams.enemyragdoll.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.enemyragdoll.occluded", "Off")
gui.SetValue("esp.chams.enemyragdoll.occluded.clr", 240, 55, 80, 255)
gui.SetValue("esp.chams.enemyragdoll.overlay", "Off")
gui.SetValue("esp.chams.enemyragdoll.overlay.clr", 239, 199, 53, 150)
gui.SetValue("esp.chams.enemyragdoll.visible", "Off")
gui.SetValue("esp.chams.enemyragdoll.visible.clr", 239, 199, 53, 255)
gui.SetValue("esp.chams.friendly" )
gui.SetValue("esp.chams.friendly.glow", "Off")
gui.SetValue("esp.chams.friendly.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.friendly.glow.healthclr1", 255, 0, 0, 255)
gui.SetValue("esp.chams.friendly.glow.healthclr2", 0, 255, 0, 255)
gui.SetValue("esp.chams.friendly.occluded", "Off")
gui.SetValue("esp.chams.friendly.occluded.clr", 48, 210, 55, 255)
gui.SetValue("esp.chams.friendly.overlay", "Off")
gui.SetValue("esp.chams.friendly.overlay.clr", 48, 194, 55, 150)
gui.SetValue("esp.chams.friendly.visible", "Off")
gui.SetValue("esp.chams.friendly.visible.clr", 41, 121, 231, 255)
gui.SetValue("esp.chams.friendlyattachments")
gui.SetValue("esp.chams.friendlyattachments.glow", "Off")
gui.SetValue("esp.chams.friendlyattachments.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.friendlyattachments.occluded", "Off")
gui.SetValue("esp.chams.friendlyattachments.occluded.clr", 41, 121, 231, 255)
gui.SetValue("esp.chams.friendlyattachments.overlay", "Off")
gui.SetValue("esp.chams.friendlyattachments.overlay.clr", 48, 194, 55, 150)
gui.SetValue("esp.chams.friendlyattachments.visible", "Off")
gui.SetValue("esp.chams.friendlyattachments.visible.clr", 48, 210, 55, 255)
gui.SetValue("esp.chams.friendlyragdoll")
gui.SetValue("esp.chams.friendlyragdoll.glow", "Off")
gui.SetValue("esp.chams.friendlyragdoll.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.friendlyragdoll.occluded", "Off")
gui.SetValue("esp.chams.friendlyragdoll.occluded.clr", 41, 121, 231, 255)
gui.SetValue("esp.chams.friendlyragdoll.overlay", "Off")
gui.SetValue("esp.chams.friendlyragdoll.overlay.clr", 48, 194, 55, 150)
gui.SetValue("esp.chams.friendlyragdoll.visible", "Off")
gui.SetValue("esp.chams.friendlyragdoll.visible.clr", 48, 210, 55, 255)
gui.SetValue("esp.chams.ghost" )
gui.SetValue("esp.chams.ghost.glow", "Off")
gui.SetValue("esp.chams.ghost.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.ghost.occluded", "Flat")
gui.SetValue("esp.chams.ghost.occluded.clr", 166, 142, 149, 20)
gui.SetValue("esp.chams.ghost.overlay", "Off")
gui.SetValue("esp.chams.ghost.overlay.clr", 147, 149, 166, 150)
gui.SetValue("esp.chams.ghost.visible", "Off")
gui.SetValue("esp.chams.ghost.visible.clr", 255, 0, 123, 28)
gui.SetValue("esp.chams.local" )
gui.SetValue("esp.chams.local.glow", "Off")
gui.SetValue("esp.chams.local.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.local.glow.healthclr1", 255, 0, 0, 255)
gui.SetValue("esp.chams.local.glow.healthclr2", 0, 255, 0, 255)
gui.SetValue("esp.chams.local.occluded", "Off")
gui.SetValue("esp.chams.local.occluded.clr", 0, 0, 0, 255)
gui.SetValue("esp.chams.local.overlay", "Off")
gui.SetValue("esp.chams.local.overlay.clr", 23, 89, 137, 150)
gui.SetValue("esp.chams.local.visible", "Glow")
gui.SetValue("esp.chams.local.visible.clr", 50, 80, 146, 71)
gui.SetValue("esp.chams.localarms" )
gui.SetValue("esp.chams.localarms.glow", "Off")
gui.SetValue("esp.chams.localarms.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.localarms.occluded", "Off")
gui.SetValue("esp.chams.localarms.occluded.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.localarms.overlay", "Off")
gui.SetValue("esp.chams.localarms.overlay.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.localarms.visible", "Off")
gui.SetValue("esp.chams.localarms.visible.clr", 84, 38, 153, 210)
gui.SetValue("esp.chams.localattachments" )
gui.SetValue("esp.chams.localattachments.glow", "Off")
gui.SetValue("esp.chams.localattachments.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.localattachments.occluded", "Off")
gui.SetValue("esp.chams.localattachments.occluded.clr", 15, 196, 255, 255)
gui.SetValue("esp.chams.localattachments.overlay", "Off")
gui.SetValue("esp.chams.localattachments.overlay.clr", 15, 153, 255, 150)
gui.SetValue("esp.chams.localattachments.visible", "Off")
gui.SetValue("esp.chams.localattachments.visible.clr", 45, 165, 200, 255)
gui.SetValue("esp.chams.localweapon" )
gui.SetValue("esp.chams.localweapon.glow", "Off")
gui.SetValue("esp.chams.localweapon.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.localweapon.occluded", "Off")
gui.SetValue("esp.chams.localweapon.occluded.clr", 18, 181, 253, 255)
gui.SetValue("esp.chams.localweapon.overlay", "Off")
gui.SetValue("esp.chams.localweapon.overlay.clr", 255, 255, 255, 23)
gui.SetValue("esp.chams.localweapon.visible", "Off")
gui.SetValue("esp.chams.localweapon.visible.clr", 45, 165, 200, 255)
gui.SetValue("esp.chams.nades" )
gui.SetValue("esp.chams.nades.glow", "Off")
gui.SetValue("esp.chams.nades.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.nades.occluded", "Color")
gui.SetValue("esp.chams.nades.occluded.clr", 255, 152, 46, 255)
gui.SetValue("esp.chams.nades.overlay", "Off")
gui.SetValue("esp.chams.nades.overlay.clr", 255, 255, 255, 150)
gui.SetValue("esp.chams.nades.visible", "Off")
gui.SetValue("esp.chams.nades.visible.clr", 255, 152, 46, 255)
gui.SetValue("esp.chams.weapon" )
gui.SetValue("esp.chams.weapon.glow", "Off")
gui.SetValue("esp.chams.weapon.glow.clr", 255, 255, 255, 255)
gui.SetValue("esp.chams.weapon.occluded", "Off")
gui.SetValue("esp.chams.weapon.occluded.clr", 102, 152, 46, 255)
gui.SetValue("esp.chams.weapon.overlay", "Off")
gui.SetValue("esp.chams.weapon.overlay.clr", 255, 255, 255, 150)
gui.SetValue("esp.chams.weapon.visible", "Off")
gui.SetValue("esp.chams.weapon.visible.clr", 102, 152, 46, 255)
gui.SetValue("esp.local")
gui.SetValue("esp.local.fov", 90.0)
gui.SetValue("esp.local.outofview", "Arrow + Info")
gui.SetValue("esp.local.outofviewscale", 40.0)
gui.SetValue("esp.local.smoothghost", "On")
gui.SetValue("esp.local.thirdperson", "On")
gui.SetValue("esp.local.thirdpersondist", 215.0)
gui.SetValue("esp.local.viewmodelfov", 54.0)
gui.SetValue("esp.local.wallbanginfo" )
gui.SetValue("esp.local.wallbanginfo.dmg", "On")
gui.SetValue("esp.local.wallbanginfo.grid", "Off")
gui.SetValue("esp.master", "On")
gui.SetValue("esp.misualstuff" )
gui.SetValue("esp.misualstuff.IndicatorResolver", "Off")
gui.SetValue("esp.misualstuff.aimbot.color", 255, 255, 255, 255)
gui.SetValue("esp.misualstuff.awall.color", 255, 255, 255, 255)
gui.SetValue("esp.misualstuff.dmg.color", 255, 23, 23, 255)
gui.SetValue("esp.misualstuff.dt.color", 255, 108, 0, 255)
gui.SetValue("esp.misualstuff.enemyammo", "On")
gui.SetValue("esp.misualstuff.fbaim.color", 255, 255, 255, 255)
gui.SetValue("esp.misualstuff.fd.color", 255, 108, 0, 255)
gui.SetValue("esp.misualstuff.fdflag", "On")
gui.SetValue("esp.misualstuff.fdi.color", 255, 23, 23, 255)
gui.SetValue("esp.misualstuff.hs.color", 0, 255, 0, 255)
gui.SetValue("esp.misualstuff.hudweapon.enabled", "On")
gui.SetValue("esp.misualstuff.hudweapon.enabled.hudweapon.color", 163, 40, 53, 255)
gui.SetValue("esp.misualstuff.hudweapon.item_1", "On")
gui.SetValue("esp.misualstuff.hudweapon.item_2", "On")
gui.SetValue("esp.misualstuff.hudweapon.item_3", "On")
gui.SetValue("esp.misualstuff.hudweapon.item_4", "On")
gui.SetValue("esp.misualstuff.hudweapon.item_5", "On")
gui.SetValue("esp.misualstuff.hudweapon.item_6", "On")
gui.SetValue("esp.misualstuff.hudweapon.item_7", "On")
gui.SetValue("esp.misualstuff.hudweapon.item_8", "On")
gui.SetValue("esp.misualstuff.indicatorAimbot", "Off")
gui.SetValue("esp.misualstuff.indicatorAwall", "Off")
gui.SetValue("esp.misualstuff.indicatorDamage", "On")
gui.SetValue("esp.misualstuff.indicatorDoubleTap", "On")
gui.SetValue("esp.misualstuff.indicatorFakeDuck", "On")
gui.SetValue("esp.misualstuff.indicatorFbaim", "Off")
gui.SetValue("esp.misualstuff.indicatorHideShots", "On")
gui.SetValue("esp.misualstuff.indicatorLegitAA", "On")
gui.SetValue("esp.misualstuff.resolver.color", 255, 255, 255, 255)
gui.SetValue("esp.misualstuff.sammo.color", 13, 19, 156, 255)
gui.SetValue("esp.other" )
gui.SetValue("esp.other.antiobs", "Off")
gui.SetValue("esp.other.antiscreenshot", "Off")
gui.SetValue("esp.other.crosshair", "Off")
gui.SetValue("esp.other.crosshair.clr", 6, 17, 113, 255)
gui.SetValue("esp.other.disablefarmodels", "Off")
gui.SetValue("esp.other.killfeed", "On")
gui.SetValue("esp.other.noflash", "On")
gui.SetValue("esp.other.nofog", "On")
gui.SetValue("esp.other.nopostprocess", "On")
gui.SetValue("esp.other.norecoil", "On")
gui.SetValue("esp.other.norenderdead", "On")
gui.SetValue("esp.other.norenderenemy", "Off")
gui.SetValue("esp.other.norenderteam", "Off")
gui.SetValue("esp.other.norenderweapon", "Off")
gui.SetValue("esp.other.noscope", "On")
gui.SetValue("esp.other.noscopedirt", "On")
gui.SetValue("esp.other.noscopeoverlay", "On")
gui.SetValue("esp.other.nosky", "Off")
gui.SetValue("esp.other.nosmoke", "On")
gui.SetValue("esp.other.radar", "Off")
gui.SetValue("esp.other.radaralpha", 255.0)
gui.SetValue("esp.other.radardist", 2300.0)
gui.SetValue("esp.other.recoilcrosshair", "Off")
gui.SetValue("esp.other.recoilcrosshair.clr", 255, 255, 255, 255)
gui.SetValue("esp.other.sharedesp", "Shared with Team")
gui.SetValue("esp.overlay" )
gui.SetValue("esp.overlay.enemy" )
gui.SetValue("esp.overlay.enemy.ammo", "Off")
gui.SetValue("esp.overlay.enemy.ammo.clr1", 0, 136, 236, 255)
gui.SetValue("esp.overlay.enemy.ammo.clr2", 0, 83, 166, 255)
gui.SetValue("esp.overlay.enemy.armor", "On")
gui.SetValue("esp.overlay.enemy.barrel", "Off")
gui.SetValue("esp.overlay.enemy.barrel.clr", 240, 60, 30, 255)
gui.SetValue("esp.overlay.enemy.box", "Off")
gui.SetValue("esp.overlay.enemy.box.clr", 173, 0, 39, 255)
gui.SetValue("esp.overlay.enemy.defusing", "On")
gui.SetValue("esp.overlay.enemy.defusing.clr", 244, 70, 66, 255)
gui.SetValue("esp.overlay.enemy.dormant", "On")
gui.SetValue("esp.overlay.enemy.flashed", "On")
gui.SetValue("esp.overlay.enemy.flashed.clr", 237, 217, 78, 255)
gui.SetValue("esp.overlay.enemy.hasc4", "On")
gui.SetValue("esp.overlay.enemy.hasc4.clr", 244, 70, 66, 255)
gui.SetValue("esp.overlay.enemy.hasdefuser", "On")
gui.SetValue("esp.overlay.enemy.hasdefuser.clr", 255, 255, 255, 255)
gui.SetValue("esp.overlay.enemy.health" )
gui.SetValue("esp.overlay.enemy.health.healthbar", "On")
gui.SetValue("esp.overlay.enemy.health.healthnum", "On")
gui.SetValue("esp.overlay.enemy.money", "Off")
gui.SetValue("esp.overlay.enemy.name", "On")
gui.SetValue("esp.overlay.enemy.planting", "On")
gui.SetValue("esp.overlay.enemy.planting.clr", 244, 70, 66, 255)
gui.SetValue("esp.overlay.enemy.precision", "On")
gui.SetValue("esp.overlay.enemy.reloading", "On")
gui.SetValue("esp.overlay.enemy.reloading.clr", 237, 217, 78, 255)
gui.SetValue("esp.overlay.enemy.scoped", "On")
gui.SetValue("esp.overlay.enemy.scoped.clr", 81, 191, 234, 255)
gui.SetValue("esp.overlay.enemy.skeleton", "Off")
gui.SetValue("esp.overlay.enemy.skeleton.clr", 240, 60, 30, 255)
gui.SetValue("esp.overlay.enemy.weapon", "Icon")
gui.SetValue("esp.overlay.enemy.weaponfilter", "Active")
gui.SetValue("esp.overlay.friendly" )
gui.SetValue("esp.overlay.friendly.ammo", "Off")
gui.SetValue("esp.overlay.friendly.ammo.clr1", 0, 136, 236, 255)
gui.SetValue("esp.overlay.friendly.ammo.clr2", 0, 83, 166, 255)
gui.SetValue("esp.overlay.friendly.armor", "Off")
gui.SetValue("esp.overlay.friendly.barrel", "Off")
gui.SetValue("esp.overlay.friendly.barrel.clr", 30, 154, 247, 255)
gui.SetValue("esp.overlay.friendly.box", "Off")
gui.SetValue("esp.overlay.friendly.box.clr", 30, 154, 247, 255)
gui.SetValue("esp.overlay.friendly.defusing", "Off")
gui.SetValue("esp.overlay.friendly.defusing.clr", 244, 70, 66, 255)
gui.SetValue("esp.overlay.friendly.dormant", "Off")
gui.SetValue("esp.overlay.friendly.flashed", "Off")
gui.SetValue("esp.overlay.friendly.flashed.clr", 237, 217, 78, 255)
gui.SetValue("esp.overlay.friendly.hasc4", "Off")
gui.SetValue("esp.overlay.friendly.hasc4.clr", 244, 70, 66, 255)
gui.SetValue("esp.overlay.friendly.hasdefuser", "Off")
gui.SetValue("esp.overlay.friendly.hasdefuser.clr", 255, 255, 255, 255)
gui.SetValue("esp.overlay.friendly.health" )
gui.SetValue("esp.overlay.friendly.health.healthbar", "Off")
gui.SetValue("esp.overlay.friendly.health.healthnum", "Off")
gui.SetValue("esp.overlay.friendly.money", "Off")
gui.SetValue("esp.overlay.friendly.name", "Off")
gui.SetValue("esp.overlay.friendly.planting", "Off")
gui.SetValue("esp.overlay.friendly.planting.clr", 244, 70, 66, 255)
gui.SetValue("esp.overlay.friendly.precision", "Off")
gui.SetValue("esp.overlay.friendly.reloading", "Off")
gui.SetValue("esp.overlay.friendly.reloading.clr", 237, 217, 78, 255)
gui.SetValue("esp.overlay.friendly.scoped", "Off")
gui.SetValue("esp.overlay.friendly.scoped.clr", 81, 191, 234, 255)
gui.SetValue("esp.overlay.friendly.skeleton", "Off")
gui.SetValue("esp.overlay.friendly.skeleton.clr", 30, 154, 247, 255)
gui.SetValue("esp.overlay.friendly.weapon", "Off")
gui.SetValue("esp.overlay.friendly.weaponfilter", "Active")
gui.SetValue("esp.overlay.weapon" )
gui.SetValue("esp.overlay.weapon.ammo", "Off")
gui.SetValue("esp.overlay.weapon.ammo.clr1", 0, 136, 236, 255)
gui.SetValue("esp.overlay.weapon.ammo.clr2", 0, 83, 166, 255)
gui.SetValue("esp.overlay.weapon.box", "Off")
gui.SetValue("esp.overlay.weapon.box.clr", 200, 200, 100, 255)
gui.SetValue("esp.overlay.weapon.c4timer", "On")
gui.SetValue("esp.overlay.weapon.defuser", "On")
gui.SetValue("esp.overlay.weapon.dzitems", "Off")
gui.SetValue("esp.overlay.weapon.dzturret", "Off")
gui.SetValue("esp.overlay.weapon.nades" )
gui.SetValue("esp.overlay.weapon.nades.icon", "Off")
gui.SetValue("esp.overlay.weapon.nades.name", "On")
gui.SetValue("esp.overlay.weapon.nades.timer", "On")
gui.SetValue("esp.overlay.weapon.name", "Icon")
gui.SetValue("esp.skins" )
gui.SetValue("esp.skins.enabled", "Off")
gui.SetValue("esp.vNothing" )
gui.SetValue("esp.world" )
gui.SetValue("esp.world.bullettracer", "Off")
gui.SetValue("esp.world.bullettracerfilter" )
gui.SetValue("esp.world.bullettracerfilter.enemy", "On")
gui.SetValue("esp.world.bullettracerfilter.enemy.clr", 240, 60, 30, 255)
gui.SetValue("esp.world.bullettracerfilter.friendly", "Off")
gui.SetValue("esp.world.bullettracerfilter.friendly.clr", 30, 154, 247, 255)
gui.SetValue("esp.world.bullettracerfilter.local", "On")
gui.SetValue("esp.world.bullettracerfilter.local.clr", 0, 255, 0, 255)
gui.SetValue("esp.world.dmgindicator", "On")
gui.SetValue("esp.world.hiteffects" )
gui.SetValue("esp.world.hiteffects.marker", "On")
gui.SetValue("esp.world.hiteffects.sound", "On")
gui.SetValue("esp.world.inferno" )
gui.SetValue("esp.world.inferno.enemy", "On")
gui.SetValue("esp.world.inferno.friendly", "Off")
gui.SetValue("esp.world.inferno.local", "On")
gui.SetValue("esp.world.materials" )
gui.SetValue("esp.world.materials.skybox", "sky_csgo_cloudy01")
gui.SetValue("esp.world.materials.skybox.clr", 255, 255, 255, 255)
gui.SetValue("esp.world.materials.staticprops", "On")
gui.SetValue("esp.world.materials.staticprops.clr", 90, 90, 90, 255)
gui.SetValue("esp.world.materials.walls", "On")
gui.SetValue("esp.world.materials.walls.clr", 43, 43, 43, 255)
gui.SetValue("esp.world.nadetracer" )
gui.SetValue("esp.world.nadetracer.enemy", "On")
gui.SetValue("esp.world.nadetracer.enemy.clr", 240, 60, 30, 255)
gui.SetValue("esp.world.nadetracer.friendly", "Off")
gui.SetValue("esp.world.nadetracer.friendly.clr", 30, 154, 247, 255)
gui.SetValue("esp.world.nadetracer.local", "On")
gui.SetValue("esp.world.nadetracer.local.clr", 0, 255, 0, 255)
gui.SetValue("esp.world.nadewarning" )
gui.SetValue("esp.world.nadewarning.enemy", "On")
gui.SetValue("esp.world.nadewarning.friendly", "Off")
gui.SetValue("esp.world.nadewarning.local", "Off")
gui.SetValue("esp.world.sounds", "On")
gui.SetValue("forcetarget", "Off")
gui.SetValue("friend" )
gui.SetValue("friend.highlight", "Off")
gui.SetValue("friend.highlight.clr", 255, 255, 255, 255)
gui.SetValue("friend.ignore", "Off")
gui.SetValue("misc" )
gui.SetValue("misc.antiuntrusted", "On")
gui.SetValue("misc.autoaccept", "On")
gui.SetValue("misc.autojump", "Perfect")
gui.SetValue("misc.autojumpbug", 0)
gui.SetValue("misc.autothrow", "Off")
gui.SetValue("misc.autothrowgrenade", 4.0)
gui.SetValue("misc.autothrowincendiary", 4.0)
gui.SetValue("misc.bypasscheats", "Off")
gui.SetValue("misc.bypasspure", "Off")
gui.SetValue("misc.chatspam", "Off")
gui.SetValue("misc.clantag", "Off")
gui.SetValue("misc.duckjump", "Off")
gui.SetValue("misc.edgejump", 0)
gui.SetValue("misc.fakelag" )
gui.SetValue("misc.fakelag.condition" )
gui.SetValue("misc.fakelag.condition.inair", "On")
gui.SetValue("misc.fakelag.condition.moving", "On")
gui.SetValue("misc.fakelag.condition.peek", "On")
gui.SetValue("misc.fakelag.condition.standing", "On")
gui.SetValue("misc.fakelag.enable", "Off")
gui.SetValue("misc.fakelag.factor", 3.0)
gui.SetValue("misc.fakelag.key", 0)
gui.SetValue("misc.fakelag.type", "Adaptive")
gui.SetValue("misc.fakelatency" )
gui.SetValue("misc.fakelatency.amount", 120.0)
gui.SetValue("misc.fakelatency.enable", "On")
gui.SetValue("misc.fakelatency.key", 0)
gui.SetValue("misc.fastduck", "Off")
gui.SetValue("misc.invisiblename", "Off")
gui.SetValue("misc.log" )
gui.SetValue("misc.log.console", "Off")
gui.SetValue("misc.log.damage" )
gui.SetValue("misc.log.damage.enemy", "On")
gui.SetValue("misc.log.damage.friendly", "Off")
gui.SetValue("misc.log.damage.local", "On")
gui.SetValue("misc.log.miss", "On")
gui.SetValue("misc.log.purchases", "On")
gui.SetValue("misc.mNothing" )
gui.SetValue("misc.master", "On")
gui.SetValue("misc.miscstuff" )
gui.SetValue("misc.miscstuff.EnableJumpScoutFix", "On")
gui.SetValue("misc.miscstuff.allowChangeValue", "Off")
gui.SetValue("misc.miscstuff.aspect.ratio.change", "Off")
gui.SetValue("misc.miscstuff.auto_speedburst_in_air", "On")
gui.SetValue("misc.miscstuff.disable_auto_jump_inair", "On")
gui.SetValue("misc.miscstuff.engineradar", "On")
gui.SetValue("misc.miscstuff.fast.ladder", "On")
gui.SetValue("misc.miscstuff.forcecrosshair", "On")
gui.SetValue("misc.miscstuff.killsay.mode", "Off")
gui.SetValue("misc.miscstuff.mSlider", 0.0)
gui.SetValue("misc.miscstuff.model.aspect", 0.0)
gui.SetValue("misc.miscstuff.model.x", 0.0)
gui.SetValue("misc.miscstuff.model.y", 0.0)
gui.SetValue("misc.miscstuff.model.z", 0.0)
gui.SetValue("misc.miscstuff.nade_activation_dist", 60.0)
gui.SetValue("misc.miscstuff.nade_back_color", 0, 0, 0, 120)
gui.SetValue("misc.miscstuff.nade_circle_color", 171, 153, 242, 255)
gui.SetValue("misc.miscstuff.nade_draw_dist", 450.0)
gui.SetValue("misc.miscstuff.nade_enable", "On")
gui.SetValue("misc.miscstuff.nade_fixpredict", "On")
gui.SetValue("misc.miscstuff.nade_fov", 10.0)
gui.SetValue("misc.miscstuff.nade_line_color", 171, 153, 242, 255)
gui.SetValue("misc.miscstuff.nade_pdraw_dist", 20.0)
gui.SetValue("misc.miscstuff.nade_text_color", 171, 153, 242, 255)
gui.SetValue("misc.miscstuff.presense.editbox", "")
gui.SetValue("misc.miscstuff.showvote", "On")
gui.SetValue("misc.miscstuff.spam.door", 0)
gui.SetValue("misc.miscstuff.stealclan", "Off")
gui.SetValue("misc.miscstuff.switch.autowall", 0)
gui.SetValue("misc.miscstuff.switch.force", 0)
gui.SetValue("misc.owreveal", "On")
gui.SetValue("misc.playerlist", "Off")
gui.SetValue("misc.rankreveal", "On")
gui.SetValue("misc.showspec", "On")
gui.SetValue("misc.slidewalk", "On")
gui.SetValue("misc.speedburst" )
gui.SetValue("misc.speedburst.enable", "Off")
gui.SetValue("misc.speedburst.indicator", "Off")
gui.SetValue("misc.speedburst.key", 69)
gui.SetValue("misc.stealname", 0)
gui.SetValue("misc.strafe" )
gui.SetValue("misc.strafe.air", "On")
gui.SetValue("misc.strafe.circle", 0)
gui.SetValue("misc.strafe.enable", "On")
gui.SetValue("misc.strafe.mode", "Normal")
gui.SetValue("misc.strafe.retrack", 2.0)
gui.SetValue("misc.strafe.snake", 0)
gui.SetValue("misc.strafe.wasd", "On")
gui.SetValue("players", 1100, 56, false)
gui.SetValue("priority", 1.0)
gui.SetValue("radar", 189, 6, 305, 333)
gui.SetValue("rbot" )
gui.SetValue("rbot.accuracy" )
gui.SetValue("rbot.accuracy.movement" )
gui.SetValue("rbot.accuracy.movement.autopeek", "On")
gui.SetValue("rbot.accuracy.movement.autopeekind", "On")
gui.SetValue("rbot.accuracy.movement.autopeekind.clr1", 0, 255, 0, 255)
gui.SetValue("rbot.accuracy.movement.autopeekind.clr2", 255, 0, 0, 255)
gui.SetValue("rbot.accuracy.movement.autopeekkey", 18)
gui.SetValue("rbot.accuracy.movement.quickstop", "On")
gui.SetValue("rbot.accuracy.movement.slowkey", 16)
gui.SetValue("rbot.accuracy.movement.slowspeed", 18.0)
gui.SetValue("rbot.accuracy.posadj" )
gui.SetValue("rbot.accuracy.posadj.backtrack", "On")
gui.SetValue("rbot.accuracy.posadj.resolver", "On")
gui.SetValue("rbot.accuracy.weapon", "Scout")
gui.SetValue("rbot.accuracy.weapon.asniper" )
gui.SetValue("rbot.accuracy.weapon.asniper.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.asniper.doublefire", "Shift")
gui.SetValue("rbot.accuracy.weapon.asniper.doublefirehc", 20.0)
gui.SetValue("rbot.accuracy.weapon.asniper.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.asniper.hitchance", 60.0)
gui.SetValue("rbot.accuracy.weapon.asniper.mindmg", 20.0)
gui.SetValue("rbot.accuracy.weapon.hpistol" )
gui.SetValue("rbot.accuracy.weapon.hpistol.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.hpistol.doublefire", "Rapid")
gui.SetValue("rbot.accuracy.weapon.hpistol.doublefirehc", 55.0)
gui.SetValue("rbot.accuracy.weapon.hpistol.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.hpistol.hitchance", 47.0)
gui.SetValue("rbot.accuracy.weapon.hpistol.mindmg", 61.0)
gui.SetValue("rbot.accuracy.weapon.lmg" )
gui.SetValue("rbot.accuracy.weapon.lmg.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.lmg.doublefire", "Rapid")
gui.SetValue("rbot.accuracy.weapon.lmg.doublefirehc", 40.0)
gui.SetValue("rbot.accuracy.weapon.lmg.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.lmg.hitchance", 35.0)
gui.SetValue("rbot.accuracy.weapon.lmg.mindmg", 15.0)
gui.SetValue("rbot.accuracy.weapon.pistol" )
gui.SetValue("rbot.accuracy.weapon.pistol.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.pistol.doublefire", "Shift")
gui.SetValue("rbot.accuracy.weapon.pistol.doublefirehc", 20.0)
gui.SetValue("rbot.accuracy.weapon.pistol.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.pistol.hitchance", 15.0)
gui.SetValue("rbot.accuracy.weapon.pistol.mindmg", 10.0)
gui.SetValue("rbot.accuracy.weapon.rifle" )
gui.SetValue("rbot.accuracy.weapon.rifle.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.rifle.doublefire", "Off")
gui.SetValue("rbot.accuracy.weapon.rifle.doublefirehc", 30.0)
gui.SetValue("rbot.accuracy.weapon.rifle.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.rifle.hitchance", 48.0)
gui.SetValue("rbot.accuracy.weapon.rifle.mindmg", 34.0)
gui.SetValue("rbot.accuracy.weapon.scout" )
gui.SetValue("rbot.accuracy.weapon.scout.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.scout.doublefire", "Rapid")
gui.SetValue("rbot.accuracy.weapon.scout.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.scout.hitchance", 70.0)
gui.SetValue("rbot.accuracy.weapon.scout.mindmg", 81.0)
gui.SetValue("rbot.accuracy.weapon.shared" )
gui.SetValue("rbot.accuracy.weapon.shared.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.shared.doublefire", "Off")
gui.SetValue("rbot.accuracy.weapon.shared.doublefirehc", 0.0)
gui.SetValue("rbot.accuracy.weapon.shared.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.shared.hitchance", 50.0)
gui.SetValue("rbot.accuracy.weapon.shared.mindmg", 50.0)
gui.SetValue("rbot.accuracy.weapon.shotgun" )
gui.SetValue("rbot.accuracy.weapon.shotgun.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.shotgun.doublefire", "Off")
gui.SetValue("rbot.accuracy.weapon.shotgun.doublefirehc", 0.0)
gui.SetValue("rbot.accuracy.weapon.shotgun.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.shotgun.hitchance", 5.0)
gui.SetValue("rbot.accuracy.weapon.shotgun.mindmg", 7.0)
gui.SetValue("rbot.accuracy.weapon.smg" )
gui.SetValue("rbot.accuracy.weapon.smg.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.smg.doublefire", "Shift")
gui.SetValue("rbot.accuracy.weapon.smg.doublefirehc", 10.0)
gui.SetValue("rbot.accuracy.weapon.smg.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.smg.hitchance", 10.0)
gui.SetValue("rbot.accuracy.weapon.smg.mindmg", 10.0)
gui.SetValue("rbot.accuracy.weapon.sniper")
gui.SetValue("rbot.accuracy.weapon.sniper.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.sniper.doublefire", "Rapid")
gui.SetValue("rbot.accuracy.weapon.sniper.doublefireind", "On")
gui.SetValue("rbot.accuracy.weapon.sniper.hitchance", 80.0)
gui.SetValue("rbot.accuracy.weapon.sniper.mindmg", 101.0)
gui.SetValue("rbot.accuracy.weapon.zeus" )
gui.SetValue("rbot.accuracy.weapon.zeus.antirecoil", "On")
gui.SetValue("rbot.accuracy.weapon.zeus.hitchance", 70.0)
gui.SetValue("rbot.accuracy.weapon.zeus.mindmg", 100.0)
gui.SetValue("rbot.accuracy.wpnmovement", "Scout")
gui.SetValue("rbot.accuracy.wpnmovement.asniper" )
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostopopts.inmolotov", "On")
gui.SetValue("rbot.accuracy.wpnmovement.asniper.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.hpistol" )
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostopopts.inmolotov", "On")
gui.SetValue("rbot.accuracy.wpnmovement.hpistol.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.lmg" )
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostopopts.inmolotov", "On")
gui.SetValue("rbot.accuracy.wpnmovement.lmg.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.pistol" )
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostopopts.inmolotov", "On")
gui.SetValue("rbot.accuracy.wpnmovement.pistol.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.rifle" )
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostopopts.inmolotov", "On")
gui.SetValue("rbot.accuracy.wpnmovement.rifle.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.scout" )
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostopopts.inmolotov", "On")
gui.SetValue("rbot.accuracy.wpnmovement.scout.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.shared" )
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostopopts.inmolotov", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shared.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.shotgun" )
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostop", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostopopts.early", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostopopts.inmolotov", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.shotgun.autostopopts.slowwalk", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.smg" )
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostop", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostopopts.early", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostopopts.inmolotov", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.smg.autostopopts.slowwalk", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.sniper" )
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostop", "On")
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostopopts.early", "On")
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostopopts.inmolotov", "On")
gui.SetValue("rbot.accuracy.wpnmovement.sniper.autostopopts.slowwalk", "On")
gui.SetValue("rbot.accuracy.wpnmovement.zeus" )
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostop", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostopopts" )
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostopopts.betweenshots", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostopopts.duck", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostopopts.early", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostopopts.inair", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostopopts.inmolotov", "Off")
gui.SetValue("rbot.accuracy.wpnmovement.zeus.autostopopts.slowwalk", "Off")
gui.SetValue("rbot.aim" )
gui.SetValue("rbot.aim.automation" )
gui.SetValue("rbot.aim.automation.pistol", "On")
gui.SetValue("rbot.aim.automation.revolver", "On")
gui.SetValue("rbot.aim.automation.scope", "On - No Unzoom")
gui.SetValue("rbot.aim.enable", "On")
gui.SetValue("rbot.aim.extra" )
gui.SetValue("rbot.aim.extra.knife", "Default Knifebot")
gui.SetValue("rbot.aim.target" )
gui.SetValue("rbot.aim.target.fov", 180.0)
gui.SetValue("rbot.aim.target.lock", "On")
gui.SetValue("rbot.aim.target.silentaim", "On")
gui.SetValue("rbot.antiaim" )
gui.SetValue("rbot.antiaim.advanced" )
gui.SetValue("rbot.antiaim.advanced.antialign", "Micromovement")
gui.SetValue("rbot.antiaim.advanced.antiresolver", "Off")
gui.SetValue("rbot.antiaim.advanced.autodir" )
gui.SetValue("rbot.antiaim.advanced.autodir.edges", "Off")
gui.SetValue("rbot.antiaim.advanced.autodir.targets", "On")
gui.SetValue("rbot.antiaim.advanced.autodirstyle", "FOV Based")
gui.SetValue("rbot.antiaim.advanced.exposefake", 0)
gui.SetValue("rbot.antiaim.advanced.exposetype", "1s")
gui.SetValue("rbot.antiaim.advanced.pitch", "89°")
gui.SetValue("rbot.antiaim.base", -166.0, "Desync")
gui.SetValue("rbot.antiaim.base.lby", 28.0)
gui.SetValue("rbot.antiaim.base.rotation", -42.0)
gui.SetValue("rbot.antiaim.base.spinspeed", 60.0)
gui.SetValue("rbot.antiaim.condition" )
gui.SetValue("rbot.antiaim.condition.freezetime", "Off")
gui.SetValue("rbot.antiaim.condition.grenade", "On")
gui.SetValue("rbot.antiaim.condition.knife", "Off")
gui.SetValue("rbot.antiaim.condition.shiftonshot", "Off")
gui.SetValue("rbot.antiaim.condition.use", "On")
gui.SetValue("rbot.antiaim.extra" )
gui.SetValue("rbot.antiaim.extra.fakecrouchkey", 67)
gui.SetValue("rbot.antiaim.extra.fakecrouchstyle", "Unduck")
gui.SetValue("rbot.antiaim.extra.staticlegs", "Off")
gui.SetValue("rbot.antiaim.left 175.0", "Desync")
gui.SetValue("rbot.antiaim.left.lby", 90.0)
gui.SetValue("rbot.antiaim.left.rotation", -58.0)
gui.SetValue("rbot.antiaim.left.spinspeed", 60.0)
gui.SetValue("rbot.antiaim.right", -175.0, "Desync")
gui.SetValue("rbot.antiaim.right.lby", -90.0)
gui.SetValue("rbot.antiaim.right.rotation", 58.0)
gui.SetValue("rbot.antiaim.right.spinspeed", 60.0)
gui.SetValue("rbot.hitscan" )
gui.SetValue("rbot.hitscan.advanced", "Scout")
gui.SetValue("rbot.hitscan.advanced.asniper" )
gui.SetValue("rbot.hitscan.advanced.asniper.precisehitscan", "On")
gui.SetValue("rbot.hitscan.advanced.asniper.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.hpistol" )
gui.SetValue("rbot.hitscan.advanced.hpistol.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.hpistol.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.lmg" )
gui.SetValue("rbot.hitscan.advanced.lmg.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.lmg.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.pistol" )
gui.SetValue("rbot.hitscan.advanced.pistol.precisehitscan", "On")
gui.SetValue("rbot.hitscan.advanced.pistol.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.rifle" )
gui.SetValue("rbot.hitscan.advanced.rifle.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.rifle.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.scout" )
gui.SetValue("rbot.hitscan.advanced.scout.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.scout.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.shared" )
gui.SetValue("rbot.hitscan.advanced.shared.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.shared.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.shotgun" )
gui.SetValue("rbot.hitscan.advanced.shotgun.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.shotgun.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.smg" )
gui.SetValue("rbot.hitscan.advanced.smg.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.smg.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.sniper" )
gui.SetValue("rbot.hitscan.advanced.sniper.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.sniper.predictive", "Off")
gui.SetValue("rbot.hitscan.advanced.zeus" )
gui.SetValue("rbot.hitscan.advanced.zeus.precisehitscan", "Off")
gui.SetValue("rbot.hitscan.advanced.zeus.predictive", "Off")
gui.SetValue("rbot.hitscan.maxprocessingtime", 65.0)
gui.SetValue("rbot.hitscan.mode", "Scout")
gui.SetValue("rbot.hitscan.mode.asniper" )
gui.SetValue("rbot.hitscan.mode.asniper.autowall", "On")
gui.SetValue("rbot.hitscan.mode.asniper.bodyaim" )
gui.SetValue("rbot.hitscan.mode.asniper.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.asniper.bodyaim.lethal", "On")
gui.SetValue("rbot.hitscan.mode.asniper.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.asniper.bodyaim.safepoint", "On")
gui.SetValue("rbot.hitscan.mode.asniper.forcesafe" )
gui.SetValue("rbot.hitscan.mode.asniper.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.asniper.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.asniper.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.asniper.prefersafe" )
gui.SetValue("rbot.hitscan.mode.asniper.prefersafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.asniper.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.asniper.prefersafe.limbs", "On")
gui.SetValue("rbot.hitscan.mode.hpistol" )
gui.SetValue("rbot.hitscan.mode.hpistol.autowall", "On")
gui.SetValue("rbot.hitscan.mode.hpistol.bodyaim" )
gui.SetValue("rbot.hitscan.mode.hpistol.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.hpistol.bodyaim.lethal", "On")
gui.SetValue("rbot.hitscan.mode.hpistol.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.hpistol.bodyaim.safepoint", "On")
gui.SetValue("rbot.hitscan.mode.hpistol.forcesafe" )
gui.SetValue("rbot.hitscan.mode.hpistol.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.hpistol.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.hpistol.forcesafe.limbs", "On")
gui.SetValue("rbot.hitscan.mode.hpistol.prefersafe")
gui.SetValue("rbot.hitscan.mode.hpistol.prefersafe.body", "On")
gui.SetValue("rbot.hitscan.mode.hpistol.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.hpistol.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.lmg" )
gui.SetValue("rbot.hitscan.mode.lmg.autowall", "On")
gui.SetValue("rbot.hitscan.mode.lmg.bodyaim" )
gui.SetValue("rbot.hitscan.mode.lmg.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.lmg.bodyaim.lethal", "On")
gui.SetValue("rbot.hitscan.mode.lmg.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.lmg.bodyaim.safepoint", "On")
gui.SetValue("rbot.hitscan.mode.lmg.forcesafe" )
gui.SetValue("rbot.hitscan.mode.lmg.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.lmg.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.lmg.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.lmg.prefersafe" )
gui.SetValue("rbot.hitscan.mode.lmg.prefersafe.body", "On")
gui.SetValue("rbot.hitscan.mode.lmg.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.lmg.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.pistol" )
gui.SetValue("rbot.hitscan.mode.pistol.autowall", "On")
gui.SetValue("rbot.hitscan.mode.pistol.bodyaim" )
gui.SetValue("rbot.hitscan.mode.pistol.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.pistol.bodyaim.lethal", "Off")
gui.SetValue("rbot.hitscan.mode.pistol.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.pistol.bodyaim.safepoint", "On")
gui.SetValue("rbot.hitscan.mode.pistol.forcesafe" )
gui.SetValue("rbot.hitscan.mode.pistol.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.pistol.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.pistol.forcesafe.limbs", "On")
gui.SetValue("rbot.hitscan.mode.pistol.prefersafe")
gui.SetValue("rbot.hitscan.mode.pistol.prefersafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.pistol.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.pistol.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.rifle" )
gui.SetValue("rbot.hitscan.mode.rifle.autowall", "On")
gui.SetValue("rbot.hitscan.mode.rifle.bodyaim" )
gui.SetValue("rbot.hitscan.mode.rifle.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.rifle.bodyaim.lethal", "Off")
gui.SetValue("rbot.hitscan.mode.rifle.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.rifle.bodyaim.safepoint", "Off")
gui.SetValue("rbot.hitscan.mode.rifle.forcesafe" )
gui.SetValue("rbot.hitscan.mode.rifle.forcesafe.body", "On")
gui.SetValue("rbot.hitscan.mode.rifle.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.rifle.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.rifle.prefersafe" )
gui.SetValue("rbot.hitscan.mode.rifle.prefersafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.rifle.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.rifle.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.scout" )
gui.SetValue("rbot.hitscan.mode.scout.autowall", "On")
gui.SetValue("rbot.hitscan.mode.scout.bodyaim")
gui.SetValue("rbot.hitscan.mode.scout.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.scout.bodyaim.lethal", "On")
gui.SetValue("rbot.hitscan.mode.scout.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.scout.bodyaim.safepoint", "Off")
gui.SetValue("rbot.hitscan.mode.scout.forcesafe" )
gui.SetValue("rbot.hitscan.mode.scout.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.scout.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.scout.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.scout.prefersafe" )
gui.SetValue("rbot.hitscan.mode.scout.prefersafe.body", "On")
gui.SetValue("rbot.hitscan.mode.scout.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.scout.prefersafe.limbs", "On")
gui.SetValue("rbot.hitscan.mode.shared" )
gui.SetValue("rbot.hitscan.mode.shared.autowall", "On")
gui.SetValue("rbot.hitscan.mode.shared.bodyaim" )
gui.SetValue("rbot.hitscan.mode.shared.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.shared.bodyaim.lethal", "Off")
gui.SetValue("rbot.hitscan.mode.shared.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.shared.bodyaim.safepoint", "Off")
gui.SetValue("rbot.hitscan.mode.shared.forcesafe" )
gui.SetValue("rbot.hitscan.mode.shared.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.shared.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.shared.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.shared.prefersafe" )
gui.SetValue("rbot.hitscan.mode.shared.prefersafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.shared.prefersafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.shared.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.shotgun" )
gui.SetValue("rbot.hitscan.mode.shotgun.autowall", "On")
gui.SetValue("rbot.hitscan.mode.shotgun.bodyaim" )
gui.SetValue("rbot.hitscan.mode.shotgun.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.shotgun.bodyaim.lethal", "Off")
gui.SetValue("rbot.hitscan.mode.shotgun.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.shotgun.bodyaim.safepoint", "On")
gui.SetValue("rbot.hitscan.mode.shotgun.forcesafe" )
gui.SetValue("rbot.hitscan.mode.shotgun.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.shotgun.forcesafe.head", "On")
gui.SetValue("rbot.hitscan.mode.shotgun.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.shotgun.prefersafe" )
gui.SetValue("rbot.hitscan.mode.shotgun.prefersafe.body", "On")
gui.SetValue("rbot.hitscan.mode.shotgun.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.shotgun.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.smg" )
gui.SetValue("rbot.hitscan.mode.smg.autowall", "On")
gui.SetValue("rbot.hitscan.mode.smg.bodyaim" )
gui.SetValue("rbot.hitscan.mode.smg.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.smg.bodyaim.lethal", "Off")
gui.SetValue("rbot.hitscan.mode.smg.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.smg.bodyaim.safepoint", "Off")
gui.SetValue("rbot.hitscan.mode.smg.forcesafe" )
gui.SetValue("rbot.hitscan.mode.smg.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.smg.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.smg.forcesafe.limbs", "On")
gui.SetValue("rbot.hitscan.mode.smg.prefersafe" )
gui.SetValue("rbot.hitscan.mode.smg.prefersafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.smg.prefersafe.head","On")
gui.SetValue("rbot.hitscan.mode.smg.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.sniper" )
gui.SetValue("rbot.hitscan.mode.sniper.autowall", "On")
gui.SetValue("rbot.hitscan.mode.sniper.bodyaim" )
gui.SetValue("rbot.hitscan.mode.sniper.bodyaim.force", "Off")
gui.SetValue("rbot.hitscan.mode.sniper.bodyaim.lethal", "On")
gui.SetValue("rbot.hitscan.mode.sniper.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.sniper.bodyaim.safepoint", "Off")
gui.SetValue("rbot.hitscan.mode.sniper.forcesafe" )
gui.SetValue("rbot.hitscan.mode.sniper.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.sniper.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.sniper.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.sniper.prefersafe" )
gui.SetValue("rbot.hitscan.mode.sniper.prefersafe.body", "On")
gui.SetValue("rbot.hitscan.mode.sniper.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.sniper.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.zeus" )
gui.SetValue("rbot.hitscan.mode.zeus.autowall", "On")
gui.SetValue("rbot.hitscan.mode.zeus.bodyaim" )
gui.SetValue("rbot.hitscan.mode.zeus.bodyaim.force", "On")
gui.SetValue("rbot.hitscan.mode.zeus.bodyaim.lethal", "Off")
gui.SetValue("rbot.hitscan.mode.zeus.bodyaim.onshot", "Off")
gui.SetValue("rbot.hitscan.mode.zeus.bodyaim.safepoint", "Off")
gui.SetValue("rbot.hitscan.mode.zeus.forcesafe" )
gui.SetValue("rbot.hitscan.mode.zeus.forcesafe.body", "Off")
gui.SetValue("rbot.hitscan.mode.zeus.forcesafe.head", "Off")
gui.SetValue("rbot.hitscan.mode.zeus.forcesafe.limbs", "Off")
gui.SetValue("rbot.hitscan.mode.zeus.prefersafe" )
gui.SetValue("rbot.hitscan.mode.zeus.prefersafe.body", "On")
gui.SetValue("rbot.hitscan.mode.zeus.prefersafe.head", "On")
gui.SetValue("rbot.hitscan.mode.zeus.prefersafe.limbs", "Off")
gui.SetValue("rbot.hitscan.points", "Scout")
gui.SetValue("rbot.hitscan.points.asniper" )
gui.SetValue("rbot.hitscan.points.asniper.scale", 2, 2, 1, 3, 3, 2, 1, 2 )
gui.SetValue("rbot.hitscan.points.hpistol" )
gui.SetValue("rbot.hitscan.points.hpistol.scale", 3, 2, 1, 2, 3, 1, 1, 2 )
gui.SetValue("rbot.hitscan.points.lmg" )
gui.SetValue("rbot.hitscan.points.lmg.scale", 2, 2, 0, 3, 3, 0, 0, 0 )
gui.SetValue("rbot.hitscan.points.pistol" )
gui.SetValue("rbot.hitscan.points.pistol.scale", 2, 1, 0, 2, 3, 0, 0, 0 )
gui.SetValue("rbot.hitscan.points.rifle" )
gui.SetValue("rbot.hitscan.points.rifle.scale", 2, 0, 0, 3, 3, 0, 0, 0 )
gui.SetValue("rbot.hitscan.points.scout" )
gui.SetValue("rbot.hitscan.points.scout.scale", 2, 1, 0, 2, 3, 1, 0, 1 )
gui.SetValue("rbot.hitscan.points.shared" )
gui.SetValue("rbot.hitscan.points.shared.scale", 1, 0, 0, 0, 0, 0, 0, 0 )
gui.SetValue("rbot.hitscan.points.shotgun" )
gui.SetValue("rbot.hitscan.points.shotgun.scale", 2, 3, 0, 3, 1, 0, 0, 0 )
gui.SetValue("rbot.hitscan.points.smg" )
gui.SetValue("rbot.hitscan.points.smg.scale", 2, 2, 0, 3, 3, 0, 0, 0 )
gui.SetValue("rbot.hitscan.points.sniper" )
gui.SetValue("rbot.hitscan.points.sniper.scale", 3, 2, 0, 2, 3, 0, 0, 0 )
gui.SetValue("rbot.hitscan.points.zeus" )
gui.SetValue("rbot.hitscan.points.zeus.scale", 1, 1, 0, 1, 1, 1, 0, 0 )
gui.SetValue("rbot.master", "On")
gui.SetValue("rbot.rNothing" )
gui.SetValue("rbot.ragestuff" )
gui.SetValue("rbot.ragestuff.attarget", "On")
gui.SetValue("rbot.ragestuff.back", 0)
gui.SetValue("rbot.ragestuff.desync_indicator", "On")
gui.SetValue("rbot.ragestuff.desync_indicator.desync_bgc", 0, 0, 0, 128)
gui.SetValue("rbot.ragestuff.desync_indicator.desync_clr", 255, 23, 23, 255)
gui.SetValue("rbot.ragestuff.enablerage", "On")
gui.SetValue("rbot.ragestuff.idealtick", "On")
gui.SetValue("rbot.ragestuff.ikey", 88)
gui.SetValue("rbot.ragestuff.jitteramount", 0.0)
gui.SetValue("rbot.ragestuff.lagsync", "On")
gui.SetValue("rbot.ragestuff.lbyangle", 120.0)
gui.SetValue("rbot.ragestuff.left", 6)
gui.SetValue("rbot.ragestuff.legitaa", "On")
gui.SetValue("rbot.ragestuff.lowdelta", "On")
gui.SetValue("rbot.ragestuff.manual_indicator", "On")
gui.SetValue("rbot.ragestuff.manual_indicator.manual_bclr", 255, 23, 23, 255)
gui.SetValue("rbot.ragestuff.manual_indicator.manual_bgc", 0, 0, 0, 128)
gui.SetValue("rbot.ragestuff.right", 5)
gui.SetValue("rbot.ragestuff.rotationangle", 58.0)
gui.SetValue("rbot.ragestuff.yawangle", 0.0)
gui.SetValue("resolver", "Default")
gui.SetValue("spectators", 1367, 0, false)
gui.SetValue("sphead", "Default")
gui.SetValue("theme" )
gui.SetValue("theme.footer" )
gui.SetValue("theme.footer.bg", 255, 21, 48, 255)
gui.SetValue("theme.footer.text", 255, 255, 255, 255)
gui.SetValue("theme.header" )
gui.SetValue("theme.header.bg", 255, 21, 48, 255)
gui.SetValue("theme.header.line", 244, 72, 72, 255)
gui.SetValue("theme.header.text", 255, 255, 255, 255)
gui.SetValue("theme.nav" )
gui.SetValue("theme.nav.active", 198, 0, 20, 84)
gui.SetValue("theme.nav.bg", 128, 0, 19, 255)
gui.SetValue("theme.nav.shadow", 54, 54, 54, 255)
gui.SetValue("theme.nav.text", 255, 255, 255, 255)
gui.SetValue("theme.tablist")
gui.SetValue("theme.tablist.shadow", 0, 0, 0, 127)
gui.SetValue("theme.tablist.tabactivebg", 198, 0, 20, 84)
gui.SetValue("theme.tablist.tabdecorator", 128, 0, 19, 255)
gui.SetValue("theme.tablist.text", 255, 255, 255, 255)
gui.SetValue("theme.tablist.textactive", 255, 6, 0, 255)
gui.SetValue("theme.ui" )
gui.SetValue("theme.ui.bg1", 20, 20, 20, 157)
gui.SetValue("theme.ui.bg2", 255, 255, 255, 255)
gui.SetValue("theme.ui.border", 255, 21, 48, 255)
gui.SetValue("unbindall")
gui.SetValue("bindtoggle", "Mouse3", "esp.local.thirdperson", "Off", "On", 0)
gui.SetValue("bindhold", "Alt", "rbot.accuracy.weapon.scout.doublefire", "Off", "Rapid", 0)
gui.SetValue("bindtoggle", "F", "rbot.accuracy.weapon.smg.doublefire", "Off", "Shift", 0)
gui.SetValue("bindtoggle", "F", "rbot.accuracy.weapon.lmg.doublefire", "Off", "Rapid", 1)
gui.SetValue("bindtoggle", "F", "rbot.accuracy.weapon.hpistol.doublefire", "Off", "Rapid", 2)
gui.SetValue("bindtoggle", "F", "rbot.accuracy.weapon.pistol.doublefire", "Off", "Shift", 3)
gui.SetValue("bindtoggle", "F", "rbot.accuracy.weapon.asniper.doublefire", "Off", "Shift", 4)
gui.SetValue("bindtoggle", "N", "rbot.antiaim.condition.shiftonshot", "Off", "On", 0)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.pistol.mindmg", "5.0", "10.0", 0)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.hpistol.mindmg", "5.0", "61.0", 1)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.smg.mindmg", "5.0", "10.0", 2)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.rifle.mindmg", "5.0", "34.0", 3)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.asniper.mindmg", "4.0", "20.0", 4)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.sniper.mindmg", "10.0", "101.0", 5)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.lmg.mindmg", "5.0", "15.0", 6)
gui.SetValue("bindtoggle", "V", "rbot.accuracy.weapon.scout.mindmg", "5.0", "81.0", 7)
gui.SetValue("unalias")
gui.SetValue("alias invertrot", "rbot.antiaim.rotation")
gui.SetValue("alias espon", "esp.overlay.enemy.name 1; esp.overlay.enemy.health.healthbar 1; esp.chams.enemy.occluded glow")
gui.SetValue("alias espoff", "esp.overlay.enemy.name 0; esp.overlay.enemy.health.healthbar 0; esp.chams.enemy.occluded off")
gui.SetValue("alias autodir1", "rbot.antiaim.left -157.0 Desync; rbot.antiaim.left.lby 100.0; rbot.antiaim.left.rotation -58.0; rbot.antiaim.right -175.0 Desync; rbot.antiaim.right.lby -100.0; rbot.antiaim.right.rotation 58.0; bindhold Mouse5 autodir2")
gui.SetValue("alias autodir2", "rbot.antiaim.left 90.0 Desync; rbot.antiaim.left.lby 0.0; rbot.antiaim.left.rotation 58.0; rbot.antiaim.right -90.0 Desync; rbot.antiaim.right.lby 0.0; rbot.antiaim.right.rotation 58.0; bindhold Mouse5 autodir1")
gui.SetValue("alias cls", "clear")
gui.SetValue("alias lyb", "rbot.antiaim.advanced.antialign")
gui.SetValue("alias micro", "rbot.antiaim.advanced.antialign")
gui.SetValue("alias hsbc", "hitscan_backtrack_only")
gui.SetValue("alias hsbc1", "hitscan_backtrack_only")
gui.SetValue("skin.clear")